"$schema" = "./node_modules/wrangler/config-schema.json"
name = "longone-ai"
main = "./worker/index.ts"
compatibility_date = "2026-04-20"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
NODE_ENV = "production"
VERTEX_TUNED_MODEL = "projects/1012420023845/locations/us-central1/endpoints/573558591361908736"
